name: Release
on:
  push:
    tags:
      - '**'

permissions:
  contents: read #  for checkout
jobs:
  release:
    permissions:
      contents: write #  to be able to publish a GitHub release
      issues: write #  to be able to comment on released issues
      pull-requests: write #  to be able to comment on released pull requests
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: lts/*
      # 缓存 node_modules
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      # 运行构建脚本
      - name: Build frontend
        run: yarn build

      # 压缩dist目录
      - name: Compressed file
        run: zip -r omsui.zip ./dist

      # 创建release文件
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "omsui.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
